`timescale 1ns / 1ps
///////////////////////////////////////////////////////////////////////////////////////
// Engineer: Rajith Senaratna
// Create Date: 11/01/2025 09:56:50 PM
// Design Name: FIR lowpass filter 317 taps
// Module Name: coeff_rom
// Target Devices: Arty s7 -50
// Description: This module loads filter coeffients values generated by python program
///////////////////////////////////////////////////////////////////////////////////////
//////////////////////////STOP/////////////////////////////////////////////////////////
//=========== Change file name & extenstion if needed (LINE 34)======================//
//======= Make sure file is in the design source folder =============================//
//======= File should contain one value per line ====================================//
/////////////////////////////////////////////////////////////////////////////////////// 
module coeff_rom#(

    parameter integer filter_coeff_width = 18, // coeff in Q1.17
    parameter integer number_taps = 159 // filter is 317 taps. bcs of symmetry 158 taps + 1 center tap
)(
    //control inputs
    input wire clk, //system clk @100MHz
    //data inputs
    input wire [7:0] address, // we have 159 entries, log2(159) = 8bits
    input wire en_read_co_eff,
    //output
    output reg signed [filter_coeff_width-1:0] coeff_out

    );
    // coeff_memory is an array of registers that works like a ROM.
    //18 bit signed regs -> 0 to 158 (159 total)
    reg signed [filter_coeff_width-1:0] coeff_memory [0:number_taps];
    
    initial begin   
        $readmemh("fir_coeffs_317_q17.mem", coeff_memory);
    end
    //synchronous read -> works like real BRAM in arty s7_50, 1 output at rising edge of the clock
    always@(posedge clk)begin
        if(en_read_co_eff)begin
            coeff_out <= coeff_memory[address];
        end
    end        
endmodule
